channels:
- conda-forge
dependencies:
- python=3.7.11
- pip
- pip:
  - mlflow
  - astunparse==1.6.3
  - cloudpickle==1.3.0
  - dill==0.3.4
  - google-cloud-bigquery-storage==1.1.0
  - google-cloud-bigquery==1.21.0
  - google-cloud-datastore==1.8.0
  - google-cloud-firestore==1.7.0
  - google-cloud-language==1.2.0
  - google-cloud-storage==1.18.1
  - google-cloud-translate==1.5.0
  - google-colab==1.0.0
  - pathlib==1.0.1
  - pydeprecate==0.3.1
  - pytorch-lightning==1.4.5
  - scipy==1.4.1
  - torch==1.9.0
  - torchtext==0.10.0
  - torchvision==0.10.0
name: mlflow-env
